project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  back-to-top-navigation: true
  navbar: false

  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - text: Home
        href: index.qmd

      - section: Foundations
        contents:
          - text: Need for MLOps
            href: need_for_mloqs.qmd
          - text: About
            href: about.qmd

  page-footer:
    center:
      - "2026, University of Washington"
      - icon: github
        href: https://github.com/

format:
  html:
    theme: zephyr
    css: styles.css
    font:
      text: "Roboto"
      heading: "Roboto"
    toc: false
    include-before-body: _includes/navbar.html
    include-after-body: scripts/theme-toggle.js
